// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfo7gm0fEsu8rOtvrA1MBRYkeZvCRqu0A',
    appId: '1:715094877913:web:5ecbf8cb09d7dd671240c8',
    messagingSenderId: '715094877913',
    projectId: 'food-1294e',
    authDomain: 'food-1294e.firebaseapp.com',
    storageBucket: 'food-1294e.firebasestorage.app',
    measurementId: 'G-41C5Q9NM6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBetjgxjmF2SDXoL-cb51BXGM9xvHjhgDo',
    appId: '1:715094877913:android:c2c6fe352d6fc86c1240c8',
    messagingSenderId: '715094877913',
    projectId: 'food-1294e',
    storageBucket: 'food-1294e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFmVBw6c0gPyjgyFDEif_ayidKMhpIqeE',
    appId: '1:715094877913:ios:cba2f5a65b42d7461240c8',
    messagingSenderId: '715094877913',
    projectId: 'food-1294e',
    storageBucket: 'food-1294e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFmVBw6c0gPyjgyFDEif_ayidKMhpIqeE',
    appId: '1:715094877913:ios:cba2f5a65b42d7461240c8',
    messagingSenderId: '715094877913',
    projectId: 'food-1294e',
    storageBucket: 'food-1294e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfo7gm0fEsu8rOtvrA1MBRYkeZvCRqu0A',
    appId: '1:715094877913:web:aba280eecc1a2b7b1240c8',
    messagingSenderId: '715094877913',
    projectId: 'food-1294e',
    authDomain: 'food-1294e.firebaseapp.com',
    storageBucket: 'food-1294e.firebasestorage.app',
    measurementId: 'G-FK8EJ6XN73',
  );
}
