// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM0M0gWITTTptoOiiErxh4xyM492R3rp8',
    appId: '1:363826705143:web:143d8e0d7022dbd6f619f2',
    messagingSenderId: '363826705143',
    projectId: 'tain-6d50f',
    authDomain: 'tain-6d50f.firebaseapp.com',
    storageBucket: 'tain-6d50f.firebasestorage.app',
    measurementId: 'G-GE69VYZ4F9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPiGLHlJ1vEfPqpyKEqc15RjhaFEB5Q0I',
    appId: '1:363826705143:android:0d11209e9be39e1df619f2',
    messagingSenderId: '363826705143',
    projectId: 'tain-6d50f',
    storageBucket: 'tain-6d50f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0vi2RYn_AeeaWsbOE94gK5AMHRY2jd9I',
    appId: '1:363826705143:ios:2c5f84653c8bf37af619f2',
    messagingSenderId: '363826705143',
    projectId: 'tain-6d50f',
    storageBucket: 'tain-6d50f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0vi2RYn_AeeaWsbOE94gK5AMHRY2jd9I',
    appId: '1:363826705143:ios:2c5f84653c8bf37af619f2',
    messagingSenderId: '363826705143',
    projectId: 'tain-6d50f',
    storageBucket: 'tain-6d50f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM0M0gWITTTptoOiiErxh4xyM492R3rp8',
    appId: '1:363826705143:web:b44c01ce72528cfaf619f2',
    messagingSenderId: '363826705143',
    projectId: 'tain-6d50f',
    authDomain: 'tain-6d50f.firebaseapp.com',
    storageBucket: 'tain-6d50f.firebasestorage.app',
    measurementId: 'G-PFC7KGTY7H',
  );

}